# Generated by Django 4.2.1 on 2023-06-15 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0002_selection'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='selection',
            constraint=models.UniqueConstraint(fields=('name', 'owner'), name='my_constraint'),
        ),
    ]
